import firebase from 'firebase/app'
import 'firebase/auth'
import 'firebase/database'
import 'firebase/storage'
import './js/config'
import './scss/main.scss'
import tplHome from './html/home.tpl.html'
import tplAbout from './html/about.tpl.html'
import tplContact from './html/contact.tpl.html'
import tplAdmin from './html/admin.tpl.html'
import tplAdminAuth from './html/admin_auth.tpl.html'

